-- Your SQL goes here
ALTER TABLE checkbot
ADD COLUMN input_tokens INTEGER NOT NULL DEFAULT 0;

ALTER TABLE checkbot
ADD COLUMN output_tokens INTEGER NOT NULL DEFAULT 0;

ALTER TABLE checkbot
ADD COLUMN total_tokens INTEGER NOT NULL DEFAULT 0;

ALTER TABLE checkbot
ADD COLUMN temperature FLOAT NOT NULL DEFAULT 0.0;
